export const colleges = [
  // Ivy League
  {
    id: 1,
    name: "Harvard University",
    location: "Cambridge, Massachusetts",
    acceptanceRate: 3.4,
    type: "ivy",
    avgGPA: 4.18,
    avgSAT: 1520,
  },
  {
    id: 2,
    name: "Yale University",
    location: "New Haven, Connecticut",
    acceptanceRate: 4.6,
    type: "ivy",
    avgGPA: 4.14,
    avgSAT: 1515,
  },
  {
    id: 3,
    name: "Princeton University",
    location: "Princeton, New Jersey",
    acceptanceRate: 4.0,
    type: "ivy",
    avgGPA: 4.16,
    avgSAT: 1510,
  },
  {
    id: 4,
    name: "Columbia University",
    location: "New York, New York",
    acceptanceRate: 3.9,
    type: "ivy",
    avgGPA: 4.15,
    avgSAT: 1505,
  },
  {
    id: 5,
    name: "University of Pennsylvania",
    location: "Philadelphia, Pennsylvania",
    acceptanceRate: 5.9,
    type: "ivy",
    avgGPA: 4.13,
    avgSAT: 1500,
  },
  {
    id: 6,
    name: "Dartmouth College",
    location: "Hanover, New Hampshire",
    acceptanceRate: 6.2,
    type: "ivy",
    avgGPA: 4.11,
    avgSAT: 1495,
  },
  {
    id: 7,
    name: "Brown University",
    location: "Providence, Rhode Island",
    acceptanceRate: 5.4,
    type: "ivy",
    avgGPA: 4.12,
    avgSAT: 1490,
  },
  {
    id: 8,
    name: "Cornell University",
    location: "Ithaca, New York",
    acceptanceRate: 7.3,
    type: "ivy",
    avgGPA: 4.07,
    avgSAT: 1480,
  },

  // Top Private Universities
  {
    id: 9,
    name: "Stanford University",
    location: "Stanford, California",
    acceptanceRate: 3.9,
    type: "private",
    avgGPA: 4.18,
    avgSAT: 1520,
  },
  {
    id: 10,
    name: "Massachusetts Institute of Technology",
    location: "Cambridge, Massachusetts",
    acceptanceRate: 4.1,
    type: "private",
    avgGPA: 4.17,
    avgSAT: 1535,
  },
  {
    id: 11,
    name: "California Institute of Technology",
    location: "Pasadena, California",
    acceptanceRate: 3.9,
    type: "private",
    avgGPA: 4.19,
    avgSAT: 1545,
  },
  {
    id: 12,
    name: "University of Chicago",
    location: "Chicago, Illinois",
    acceptanceRate: 5.4,
    type: "private",
    avgGPA: 4.13,
    avgSAT: 1520,
  },
  {
    id: 13,
    name: "Northwestern University",
    location: "Evanston, Illinois",
    acceptanceRate: 7.0,
    type: "private",
    avgGPA: 4.1,
    avgSAT: 1490,
  },
  {
    id: 14,
    name: "Johns Hopkins University",
    location: "Baltimore, Maryland",
    acceptanceRate: 7.5,
    type: "private",
    avgGPA: 4.11,
    avgSAT: 1500,
  },
  {
    id: 15,
    name: "Duke University",
    location: "Durham, North Carolina",
    acceptanceRate: 6.2,
    type: "private",
    avgGPA: 4.13,
    avgSAT: 1510,
  },
  {
    id: 16,
    name: "Vanderbilt University",
    location: "Nashville, Tennessee",
    acceptanceRate: 6.7,
    type: "private",
    avgGPA: 4.09,
    avgSAT: 1480,
  },
  {
    id: 17,
    name: "Rice University",
    location: "Houston, Texas",
    acceptanceRate: 8.7,
    type: "private",
    avgGPA: 4.12,
    avgSAT: 1500,
  },
  {
    id: 18,
    name: "Washington University in St. Louis",
    location: "St. Louis, Missouri",
    acceptanceRate: 11.9,
    type: "private",
    avgGPA: 4.15,
    avgSAT: 1520,
  },
  {
    id: 19,
    name: "Emory University",
    location: "Atlanta, Georgia",
    acceptanceRate: 13.1,
    type: "private",
    avgGPA: 4.07,
    avgSAT: 1460,
  },
  {
    id: 20,
    name: "Georgetown University",
    location: "Washington, D.C.",
    acceptanceRate: 12.2,
    type: "private",
    avgGPA: 4.01,
    avgSAT: 1450,
  },

  // Top Public Universities
  {
    id: 21,
    name: "University of California, Berkeley",
    location: "Berkeley, California",
    acceptanceRate: 11.4,
    type: "public",
    avgGPA: 4.15,
    avgSAT: 1415,
  },
  {
    id: 22,
    name: "University of California, Los Angeles",
    location: "Los Angeles, California",
    acceptanceRate: 10.8,
    type: "public",
    avgGPA: 4.18,
    avgSAT: 1405,
  },
  {
    id: 23,
    name: "University of Michigan",
    location: "Ann Arbor, Michigan",
    acceptanceRate: 18.9,
    type: "public",
    avgGPA: 4.0,
    avgSAT: 1400,
  },
  {
    id: 24,
    name: "University of Virginia",
    location: "Charlottesville, Virginia",
    acceptanceRate: 21.0,
    type: "public",
    avgGPA: 4.04,
    avgSAT: 1420,
  },
  {
    id: 25,
    name: "University of North Carolina at Chapel Hill",
    location: "Chapel Hill, North Carolina",
    acceptanceRate: 16.8,
    type: "public",
    avgGPA: 4.39,
    avgSAT: 1350,
  },
  {
    id: 26,
    name: "Georgia Institute of Technology",
    location: "Atlanta, Georgia",
    acceptanceRate: 16.9,
    type: "public",
    avgGPA: 4.07,
    avgSAT: 1435,
  },
  {
    id: 27,
    name: "University of California, San Diego",
    location: "San Diego, California",
    acceptanceRate: 23.7,
    type: "public",
    avgGPA: 4.08,
    avgSAT: 1370,
  },
  {
    id: 28,
    name: "University of Florida",
    location: "Gainesville, Florida",
    acceptanceRate: 23.0,
    type: "public",
    avgGPA: 4.42,
    avgSAT: 1350,
  },
  {
    id: 29,
    name: "University of Texas at Austin",
    location: "Austin, Texas",
    acceptanceRate: 31.8,
    type: "public",
    avgGPA: 3.84,
    avgSAT: 1355,
  },
  {
    id: 30,
    name: "University of Wisconsin-Madison",
    location: "Madison, Wisconsin",
    acceptanceRate: 39.1,
    type: "public",
    avgGPA: 3.88,
    avgSAT: 1350,
  },

  // More Private Universities
  {
    id: 31,
    name: "Carnegie Mellon University",
    location: "Pittsburgh, Pennsylvania",
    acceptanceRate: 11.3,
    type: "private",
    avgGPA: 4.04,
    avgSAT: 1480,
  },
  {
    id: 32,
    name: "University of Notre Dame",
    location: "Notre Dame, Indiana",
    acceptanceRate: 15.8,
    type: "private",
    avgGPA: 4.06,
    avgSAT: 1445,
  },
  {
    id: 33,
    name: "Wake Forest University",
    location: "Winston-Salem, North Carolina",
    acceptanceRate: 25.6,
    type: "private",
    avgGPA: 3.74,
    avgSAT: 1380,
  },
  {
    id: 34,
    name: "Tufts University",
    location: "Medford, Massachusetts",
    acceptanceRate: 9.7,
    type: "private",
    avgGPA: 4.04,
    avgSAT: 1465,
  },
  {
    id: 35,
    name: "Boston College",
    location: "Chestnut Hill, Massachusetts",
    acceptanceRate: 17.3,
    type: "private",
    avgGPA: 3.96,
    avgSAT: 1420,
  },
  {
    id: 36,
    name: "New York University",
    location: "New York, New York",
    acceptanceRate: 12.8,
    type: "private",
    avgGPA: 3.69,
    avgSAT: 1370,
  },
  {
    id: 37,
    name: "University of Southern California",
    location: "Los Angeles, California",
    acceptanceRate: 12.4,
    type: "private",
    avgGPA: 3.79,
    avgSAT: 1435,
  },
  {
    id: 38,
    name: "Northeastern University",
    location: "Boston, Massachusetts",
    acceptanceRate: 18.1,
    type: "private",
    avgGPA: 4.04,
    avgSAT: 1465,
  },
  {
    id: 39,
    name: "Case Western Reserve University",
    location: "Cleveland, Ohio",
    acceptanceRate: 27.7,
    type: "private",
    avgGPA: 4.12,
    avgSAT: 1470,
  },
  {
    id: 40,
    name: "Tulane University",
    location: "New Orleans, Louisiana",
    acceptanceRate: 11.5,
    type: "private",
    avgGPA: 3.56,
    avgSAT: 1410,
  },

  // More Public Universities
  {
    id: 41,
    name: "University of California, Irvine",
    location: "Irvine, California",
    acceptanceRate: 21.3,
    type: "public",
    avgGPA: 4.0,
    avgSAT: 1295,
  },
  {
    id: 42,
    name: "University of California, Davis",
    location: "Davis, California",
    acceptanceRate: 38.9,
    type: "public",
    avgGPA: 4.03,
    avgSAT: 1290,
  },
  {
    id: 43,
    name: "University of California, Santa Barbara",
    location: "Santa Barbara, California",
    acceptanceRate: 25.9,
    type: "public",
    avgGPA: 4.15,
    avgSAT: 1320,
  },
  {
    id: 44,
    name: "University of Washington",
    location: "Seattle, Washington",
    acceptanceRate: 48.0,
    type: "public",
    avgGPA: 3.8,
    avgSAT: 1220,
  },
  {
    id: 45,
    name: "University of Illinois at Urbana-Champaign",
    location: "Champaign, Illinois",
    acceptanceRate: 45.1,
    type: "public",
    avgGPA: 3.83,
    avgSAT: 1330,
  },
  {
    id: 46,
    name: "Ohio State University",
    location: "Columbus, Ohio",
    acceptanceRate: 57.0,
    type: "public",
    avgGPA: 3.83,
    avgSAT: 1240,
  },
  {
    id: 47,
    name: "Pennsylvania State University",
    location: "University Park, Pennsylvania",
    acceptanceRate: 55.2,
    type: "public",
    avgGPA: 3.67,
    avgSAT: 1265,
  },
  {
    id: 48,
    name: "University of Maryland",
    location: "College Park, Maryland",
    acceptanceRate: 44.2,
    type: "public",
    avgGPA: 4.32,
    avgSAT: 1330,
  },
  {
    id: 49,
    name: "Purdue University",
    location: "West Lafayette, Indiana",
    acceptanceRate: 69.0,
    type: "public",
    avgGPA: 3.74,
    avgSAT: 1330,
  },
  {
    id: 50,
    name: "University of Georgia",
    location: "Athens, Georgia",
    acceptanceRate: 42.5,
    type: "public",
    avgGPA: 4.0,
    avgSAT: 1240,
  },

  // Liberal Arts Colleges
  {
    id: 51,
    name: "Williams College",
    location: "Williamstown, Massachusetts",
    acceptanceRate: 8.1,
    type: "private",
    avgGPA: 4.05,
    avgSAT: 1480,
  },
  {
    id: 52,
    name: "Amherst College",
    location: "Amherst, Massachusetts",
    acceptanceRate: 7.8,
    type: "private",
    avgGPA: 4.1,
    avgSAT: 1495,
  },
  {
    id: 53,
    name: "Swarthmore College",
    location: "Swarthmore, Pennsylvania",
    acceptanceRate: 6.9,
    type: "private",
    avgGPA: 4.09,
    avgSAT: 1485,
  },
  {
    id: 54,
    name: "Wellesley College",
    location: "Wellesley, Massachusetts",
    acceptanceRate: 16.4,
    type: "private",
    avgGPA: 3.91,
    avgSAT: 1420,
  },
  {
    id: 55,
    name: "Pomona College",
    location: "Claremont, California",
    acceptanceRate: 7.2,
    type: "private",
    avgGPA: 4.05,
    avgSAT: 1470,
  },
  {
    id: 56,
    name: "Bowdoin College",
    location: "Brunswick, Maine",
    acceptanceRate: 9.0,
    type: "private",
    avgGPA: 3.95,
    avgSAT: 1435,
  },
  {
    id: 57,
    name: "Middlebury College",
    location: "Middlebury, Vermont",
    acceptanceRate: 13.0,
    type: "private",
    avgGPA: 3.89,
    avgSAT: 1425,
  },
  {
    id: 58,
    name: "Carleton College",
    location: "Northfield, Minnesota",
    acceptanceRate: 15.1,
    type: "private",
    avgGPA: 3.9,
    avgSAT: 1450,
  },
  {
    id: 59,
    name: "Davidson College",
    location: "Davidson, North Carolina",
    acceptanceRate: 17.1,
    type: "private",
    avgGPA: 3.91,
    avgSAT: 1405,
  },
  {
    id: 60,
    name: "Haverford College",
    location: "Haverford, Pennsylvania",
    acceptanceRate: 16.8,
    type: "private",
    avgGPA: 3.9,
    avgSAT: 1465,
  },

  // More Universities (continuing to reach 200+)
  {
    id: 61,
    name: "Boston University",
    location: "Boston, Massachusetts",
    acceptanceRate: 18.9,
    type: "private",
    avgGPA: 3.71,
    avgSAT: 1405,
  },
  {
    id: 62,
    name: "Brandeis University",
    location: "Waltham, Massachusetts",
    acceptanceRate: 31.1,
    type: "private",
    avgGPA: 3.89,
    avgSAT: 1435,
  },
  {
    id: 63,
    name: "University of Rochester",
    location: "Rochester, New York",
    acceptanceRate: 39.0,
    type: "private",
    avgGPA: 3.78,
    avgSAT: 1370,
  },
  {
    id: 64,
    name: "Lehigh University",
    location: "Bethlehem, Pennsylvania",
    acceptanceRate: 32.0,
    type: "private",
    avgGPA: 3.91,
    avgSAT: 1365,
  },
  {
    id: 65,
    name: "Villanova University",
    location: "Villanova, Pennsylvania",
    acceptanceRate: 25.5,
    type: "private",
    avgGPA: 3.89,
    avgSAT: 1420,
  },
  {
    id: 66,
    name: "University of Miami",
    location: "Coral Gables, Florida",
    acceptanceRate: 27.5,
    type: "private",
    avgGPA: 3.7,
    avgSAT: 1360,
  },
  {
    id: 67,
    name: "Syracuse University",
    location: "Syracuse, New York",
    acceptanceRate: 44.4,
    type: "private",
    avgGPA: 3.67,
    avgSAT: 1270,
  },
  {
    id: 68,
    name: "Rensselaer Polytechnic Institute",
    location: "Troy, New York",
    acceptanceRate: 43.0,
    type: "private",
    avgGPA: 3.91,
    avgSAT: 1435,
  },
  {
    id: 69,
    name: "University of Richmond",
    location: "Richmond, Virginia",
    acceptanceRate: 24.0,
    type: "private",
    avgGPA: 3.76,
    avgSAT: 1350,
  },
  {
    id: 70,
    name: "Colgate University",
    location: "Hamilton, New York",
    acceptanceRate: 17.2,
    type: "private",
    avgGPA: 3.68,
    avgSAT: 1410,
  },

  // State Universities
  {
    id: 71,
    name: "University of Connecticut",
    location: "Storrs, Connecticut",
    acceptanceRate: 56.0,
    type: "public",
    avgGPA: 3.76,
    avgSAT: 1210,
  },
  {
    id: 72,
    name: "University of Delaware",
    location: "Newark, Delaware",
    acceptanceRate: 66.9,
    type: "public",
    avgGPA: 3.69,
    avgSAT: 1280,
  },
  {
    id: 73,
    name: "University of Vermont",
    location: "Burlington, Vermont",
    acceptanceRate: 67.4,
    type: "public",
    avgGPA: 3.61,
    avgSAT: 1240,
  },
  {
    id: 74,
    name: "University of New Hampshire",
    location: "Durham, New Hampshire",
    acceptanceRate: 87.0,
    type: "public",
    avgGPA: 3.3,
    avgSAT: 1150,
  },
  {
    id: 75,
    name: "University of Maine",
    location: "Orono, Maine",
    acceptanceRate: 94.0,
    type: "public",
    avgGPA: 3.3,
    avgSAT: 1140,
  },
  {
    id: 76,
    name: "University of Rhode Island",
    location: "Kingston, Rhode Island",
    acceptanceRate: 76.4,
    type: "public",
    avgGPA: 3.5,
    avgSAT: 1180,
  },
  {
    id: 77,
    name: "University of Massachusetts Amherst",
    location: "Amherst, Massachusetts",
    acceptanceRate: 64.2,
    type: "public",
    avgGPA: 3.9,
    avgSAT: 1330,
  },
  {
    id: 78,
    name: "Rutgers University",
    location: "New Brunswick, New Jersey",
    acceptanceRate: 66.3,
    type: "public",
    avgGPA: 3.73,
    avgSAT: 1270,
  },
  {
    id: 79,
    name: "SUNY Binghamton",
    location: "Binghamton, New York",
    acceptanceRate: 44.0,
    type: "public",
    avgGPA: 3.7,
    avgSAT: 1370,
  },
  {
    id: 80,
    name: "SUNY Stony Brook",
    location: "Stony Brook, New York",
    acceptanceRate: 49.1,
    type: "public",
    avgGPA: 3.8,
    avgSAT: 1350,
  },

  // More colleges to reach 200+
  {
    id: 81,
    name: "Colby College",
    location: "Waterville, Maine",
    acceptanceRate: 10.2,
    type: "private",
    avgGPA: 3.88,
    avgSAT: 1420,
  },
  {
    id: 82,
    name: "Hamilton College",
    location: "Clinton, New York",
    acceptanceRate: 12.2,
    type: "private",
    avgGPA: 3.85,
    avgSAT: 1440,
  },
  {
    id: 83,
    name: "Bates College",
    location: "Lewiston, Maine",
    acceptanceRate: 12.1,
    type: "private",
    avgGPA: 3.89,
    avgSAT: 1380,
  },
  {
    id: 84,
    name: "Grinnell College",
    location: "Grinnell, Iowa",
    acceptanceRate: 10.8,
    type: "private",
    avgGPA: 3.9,
    avgSAT: 1465,
  },
  {
    id: 85,
    name: "Macalester College",
    location: "Saint Paul, Minnesota",
    acceptanceRate: 26.9,
    type: "private",
    avgGPA: 3.85,
    avgSAT: 1350,
  },
  {
    id: 86,
    name: "Oberlin College",
    location: "Oberlin, Ohio",
    acceptanceRate: 35.2,
    type: "private",
    avgGPA: 3.6,
    avgSAT: 1350,
  },
  {
    id: 87,
    name: "Reed College",
    location: "Portland, Oregon",
    acceptanceRate: 30.8,
    type: "private",
    avgGPA: 3.9,
    avgSAT: 1420,
  },
  {
    id: 88,
    name: "Vassar College",
    location: "Poughkeepsie, New York",
    acceptanceRate: 20.4,
    type: "private",
    avgGPA: 3.85,
    avgSAT: 1415,
  },
  {
    id: 89,
    name: "Wesleyan University",
    location: "Middletown, Connecticut",
    acceptanceRate: 15.8,
    type: "private",
    avgGPA: 3.89,
    avgSAT: 1420,
  },
  {
    id: 90,
    name: "Colorado College",
    location: "Colorado Springs, Colorado",
    acceptanceRate: 13.4,
    type: "private",
    avgGPA: 3.87,
    avgSAT: 1380,
  },

  // Additional universities to expand the list
  {
    id: 91,
    name: "University of Alabama",
    location: "Tuscaloosa, Alabama",
    acceptanceRate: 83.0,
    type: "public",
    avgGPA: 3.71,
    avgSAT: 1240,
  },
  {
    id: 92,
    name: "Auburn University",
    location: "Auburn, Alabama",
    acceptanceRate: 85.0,
    type: "public",
    avgGPA: 3.89,
    avgSAT: 1240,
  },
  {
    id: 93,
    name: "University of Arkansas",
    location: "Fayetteville, Arkansas",
    acceptanceRate: 78.0,
    type: "public",
    avgGPA: 3.62,
    avgSAT: 1190,
  },
  {
    id: 94,
    name: "Arizona State University",
    location: "Tempe, Arizona",
    acceptanceRate: 88.0,
    type: "public",
    avgGPA: 3.54,
    avgSAT: 1120,
  },
  {
    id: 95,
    name: "University of Arizona",
    location: "Tucson, Arizona",
    acceptanceRate: 87.0,
    type: "public",
    avgGPA: 3.39,
    avgSAT: 1140,
  },
  {
    id: 96,
    name: "University of Colorado Boulder",
    location: "Boulder, Colorado",
    acceptanceRate: 84.0,
    type: "public",
    avgGPA: 3.69,
    avgSAT: 1240,
  },
  {
    id: 97,
    name: "Colorado State University",
    location: "Fort Collins, Colorado",
    acceptanceRate: 91.0,
    type: "public",
    avgGPA: 3.59,
    avgSAT: 1150,
  },
  {
    id: 98,
    name: "University of Idaho",
    location: "Moscow, Idaho",
    acceptanceRate: 74.0,
    type: "public",
    avgGPA: 3.5,
    avgSAT: 1080,
  },
  {
    id: 99,
    name: "Boise State University",
    location: "Boise, Idaho",
    acceptanceRate: 84.0,
    type: "public",
    avgGPA: 3.54,
    avgSAT: 1090,
  },
  {
    id: 100,
    name: "University of Iowa",
    location: "Iowa City, Iowa",
    acceptanceRate: 86.0,
    type: "public",
    avgGPA: 3.73,
    avgSAT: 1230,
  },

  // Continue with more universities
  {
    id: 101,
    name: "Iowa State University",
    location: "Ames, Iowa",
    acceptanceRate: 92.0,
    type: "public",
    avgGPA: 3.78,
    avgSAT: 1160,
  },
  {
    id: 102,
    name: "University of Kansas",
    location: "Lawrence, Kansas",
    acceptanceRate: 93.0,
    type: "public",
    avgGPA: 3.39,
    avgSAT: 1150,
  },
  {
    id: 103,
    name: "Kansas State University",
    location: "Manhattan, Kansas",
    acceptanceRate: 95.0,
    type: "public",
    avgGPA: 3.51,
    avgSAT: 1080,
  },
  {
    id: 104,
    name: "University of Kentucky",
    location: "Lexington, Kentucky",
    acceptanceRate: 96.0,
    type: "public",
    avgGPA: 3.61,
    avgSAT: 1150,
  },
  {
    id: 105,
    name: "Louisiana State University",
    location: "Baton Rouge, Louisiana",
    acceptanceRate: 76.0,
    type: "public",
    avgGPA: 3.5,
    avgSAT: 1210,
  },
  {
    id: 106,
    name: "University of Mississippi",
    location: "Oxford, Mississippi",
    acceptanceRate: 88.0,
    type: "public",
    avgGPA: 3.6,
    avgSAT: 1240,
  },
  {
    id: 107,
    name: "Mississippi State University",
    location: "Starkville, Mississippi",
    acceptanceRate: 75.0,
    type: "public",
    avgGPA: 3.6,
    avgSAT: 1190,
  },
  {
    id: 108,
    name: "University of Missouri",
    location: "Columbia, Missouri",
    acceptanceRate: 79.0,
    type: "public",
    avgGPA: 3.51,
    avgSAT: 1190,
  },
  {
    id: 109,
    name: "University of Montana",
    location: "Missoula, Montana",
    acceptanceRate: 95.0,
    type: "public",
    avgGPA: 3.46,
    avgSAT: 1080,
  },
  {
    id: 110,
    name: "Montana State University",
    location: "Bozeman, Montana",
    acceptanceRate: 73.0,
    type: "public",
    avgGPA: 3.64,
    avgSAT: 1180,
  },

  // More universities
  {
    id: 111,
    name: "University of Nebraska",
    location: "Lincoln, Nebraska",
    acceptanceRate: 79.0,
    type: "public",
    avgGPA: 3.61,
    avgSAT: 1190,
  },
  {
    id: 112,
    name: "University of Nevada, Las Vegas",
    location: "Las Vegas, Nevada",
    acceptanceRate: 85.0,
    type: "public",
    avgGPA: 3.39,
    avgSAT: 1040,
  },
  {
    id: 113,
    name: "University of Nevada, Reno",
    location: "Reno, Nevada",
    acceptanceRate: 86.0,
    type: "public",
    avgGPA: 3.55,
    avgSAT: 1120,
  },
  {
    id: 114,
    name: "University of New Mexico",
    location: "Albuquerque, New Mexico",
    acceptanceRate: 96.0,
    type: "public",
    avgGPA: 3.37,
    avgSAT: 1030,
  },
  {
    id: 115,
    name: "University of North Dakota",
    location: "Grand Forks, North Dakota",
    acceptanceRate: 83.0,
    type: "public",
    avgGPA: 3.46,
    avgSAT: 1120,
  },
  {
    id: 116,
    name: "North Dakota State University",
    location: "Fargo, North Dakota",
    acceptanceRate: 96.0,
    type: "public",
    avgGPA: 3.49,
    avgSAT: 1160,
  },
  {
    id: 117,
    name: "University of Oklahoma",
    location: "Norman, Oklahoma",
    acceptanceRate: 69.0,
    type: "public",
    avgGPA: 3.62,
    avgSAT: 1240,
  },
  {
    id: 118,
    name: "Oklahoma State University",
    location: "Stillwater, Oklahoma",
    acceptanceRate: 71.0,
    type: "public",
    avgGPA: 3.58,
    avgSAT: 1160,
  },
  {
    id: 119,
    name: "Oregon State University",
    location: "Corvallis, Oregon",
    acceptanceRate: 82.0,
    type: "public",
    avgGPA: 3.59,
    avgSAT: 1180,
  },
  {
    id: 120,
    name: "University of Oregon",
    location: "Eugene, Oregon",
    acceptanceRate: 84.0,
    type: "public",
    avgGPA: 3.59,
    avgSAT: 1210,
  },

  // Continue with more universities
  {
    id: 121,
    name: "University of South Carolina",
    location: "Columbia, South Carolina",
    acceptanceRate: 69.0,
    type: "public",
    avgGPA: 4.15,
    avgSAT: 1240,
  },
  {
    id: 122,
    name: "Clemson University",
    location: "Clemson, South Carolina",
    acceptanceRate: 43.0,
    type: "public",
    avgGPA: 4.09,
    avgSAT: 1240,
  },
  {
    id: 123,
    name: "University of South Dakota",
    location: "Vermillion, South Dakota",
    acceptanceRate: 88.0,
    type: "public",
    avgGPA: 3.53,
    avgSAT: 1120,
  },
  {
    id: 124,
    name: "South Dakota State University",
    location: "Brookings, South Dakota",
    acceptanceRate: 92.0,
    type: "public",
    avgGPA: 3.56,
    avgSAT: 1140,
  },
  {
    id: 125,
    name: "University of Tennessee",
    location: "Knoxville, Tennessee",
    acceptanceRate: 68.0,
    type: "public",
    avgGPA: 4.12,
    avgSAT: 1240,
  },
  {
    id: 126,
    name: "University of Utah",
    location: "Salt Lake City, Utah",
    acceptanceRate: 89.0,
    type: "public",
    avgGPA: 3.66,
    avgSAT: 1210,
  },
  {
    id: 127,
    name: "Utah State University",
    location: "Logan, Utah",
    acceptanceRate: 94.0,
    type: "public",
    avgGPA: 3.58,
    avgSAT: 1120,
  },
  {
    id: 128,
    name: "Virginia Tech",
    location: "Blacksburg, Virginia",
    acceptanceRate: 65.0,
    type: "public",
    avgGPA: 4.04,
    avgSAT: 1270,
  },
  {
    id: 129,
    name: "James Madison University",
    location: "Harrisonburg, Virginia",
    acceptanceRate: 78.0,
    type: "public",
    avgGPA: 3.55,
    avgSAT: 1150,
  },
  {
    id: 130,
    name: "Washington State University",
    location: "Pullman, Washington",
    acceptanceRate: 76.0,
    type: "public",
    avgGPA: 3.42,
    avgSAT: 1090,
  },

  // More private colleges
  {
    id: 131,
    name: "Pepperdine University",
    location: "Malibu, California",
    acceptanceRate: 31.0,
    type: "private",
    avgGPA: 3.66,
    avgSAT: 1340,
  },
  {
    id: 132,
    name: "Santa Clara University",
    location: "Santa Clara, California",
    acceptanceRate: 49.0,
    type: "private",
    avgGPA: 3.69,
    avgSAT: 1320,
  },
  {
    id: 133,
    name: "Loyola Marymount University",
    location: "Los Angeles, California",
    acceptanceRate: 44.0,
    type: "private",
    avgGPA: 3.73,
    avgSAT: 1290,
  },
  {
    id: 134,
    name: "University of San Diego",
    location: "San Diego, California",
    acceptanceRate: 49.0,
    type: "private",
    avgGPA: 3.85,
    avgSAT: 1270,
  },
  {
    id: 135,
    name: "Chapman University",
    location: "Orange, California",
    acceptanceRate: 58.0,
    type: "private",
    avgGPA: 3.73,
    avgSAT: 1240,
  },
  {
    id: 136,
    name: "Occidental College",
    location: "Los Angeles, California",
    acceptanceRate: 37.0,
    type: "private",
    avgGPA: 3.64,
    avgSAT: 1350,
  },
  {
    id: 137,
    name: "University of the Pacific",
    location: "Stockton, California",
    acceptanceRate: 93.0,
    type: "private",
    avgGPA: 3.61,
    avgSAT: 1180,
  },
  {
    id: 138,
    name: "Whittier College",
    location: "Whittier, California",
    acceptanceRate: 75.0,
    type: "private",
    avgGPA: 3.46,
    avgSAT: 1120,
  },
  {
    id: 139,
    name: "University of Redlands",
    location: "Redlands, California",
    acceptanceRate: 81.0,
    type: "private",
    avgGPA: 3.6,
    avgSAT: 1180,
  },
  {
    id: 140,
    name: "Mills College",
    location: "Oakland, California",
    acceptanceRate: 91.0,
    type: "private",
    avgGPA: 3.68,
    avgSAT: 1180,
  },

  // East Coast private colleges
  {
    id: 141,
    name: "Babson College",
    location: "Wellesley, Massachusetts",
    acceptanceRate: 22.0,
    type: "private",
    avgGPA: 3.86,
    avgSAT: 1370,
  },
  {
    id: 142,
    name: "Bentley University",
    location: "Waltham, Massachusetts",
    acceptanceRate: 58.0,
    type: "private",
    avgGPA: 3.73,
    avgSAT: 1280,
  },
  {
    id: 143,
    name: "Emerson College",
    location: "Boston, Massachusetts",
    acceptanceRate: 36.0,
    type: "private",
    avgGPA: 3.72,
    avgSAT: 1240,
  },
  {
    id: 144,
    name: "Suffolk University",
    location: "Boston, Massachusetts",
    acceptanceRate: 86.0,
    type: "private",
    avgGPA: 3.13,
    avgSAT: 1080,
  },
  {
    id: 145,
    name: "Simmons University",
    location: "Boston, Massachusetts",
    acceptanceRate: 85.0,
    type: "private",
    avgGPA: 3.67,
    avgSAT: 1180,
  },
  {
    id: 146,
    name: "Clark University",
    location: "Worcester, Massachusetts",
    acceptanceRate: 69.0,
    type: "private",
    avgGPA: 3.64,
    avgSAT: 1240,
  },
  {
    id: 147,
    name: "Worcester Polytechnic Institute",
    location: "Worcester, Massachusetts",
    acceptanceRate: 57.0,
    type: "private",
    avgGPA: 3.9,
    avgSAT: 1420,
  },
  {
    id: 148,
    name: "Assumption University",
    location: "Worcester, Massachusetts",
    acceptanceRate: 81.0,
    type: "private",
    avgGPA: 3.36,
    avgSAT: 1140,
  },
  {
    id: 149,
    name: "Stonehill College",
    location: "Easton, Massachusetts",
    acceptanceRate: 73.0,
    type: "private",
    avgGPA: 3.36,
    avgSAT: 1180,
  },
  {
    id: 150,
    name: "Merrimack College",
    location: "North Andover, Massachusetts",
    acceptanceRate: 84.0,
    type: "private",
    avgGPA: 3.29,
    avgSAT: 1120,
  },

  // Mid-Atlantic private colleges
  {
    id: 151,
    name: "Gettysburg College",
    location: "Gettysburg, Pennsylvania",
    acceptanceRate: 60.0,
    type: "private",
    avgGPA: 3.64,
    avgSAT: 1280,
  },
  {
    id: 152,
    name: "Dickinson College",
    location: "Carlisle, Pennsylvania",
    acceptanceRate: 41.0,
    type: "private",
    avgGPA: 3.7,
    avgSAT: 1320,
  },
  {
    id: 153,
    name: "Franklin & Marshall College",
    location: "Lancaster, Pennsylvania",
    acceptanceRate: 30.0,
    type: "private",
    avgGPA: 3.64,
    avgSAT: 1350,
  },
  {
    id: 154,
    name: "Lafayette College",
    location: "Easton, Pennsylvania",
    acceptanceRate: 28.0,
    type: "private",
    avgGPA: 3.52,
    avgSAT: 1350,
  },
  {
    id: 155,
    name: "Bucknell University",
    location: "Lewisburg, Pennsylvania",
    acceptanceRate: 33.0,
    type: "private",
    avgGPA: 3.86,
    avgSAT: 1370,
  },
  {
    id: 156,
    name: "Muhlenberg College",
    location: "Allentown, Pennsylvania",
    acceptanceRate: 66.0,
    type: "private",
    avgGPA: 3.34,
    avgSAT: 1240,
  },
  {
    id: 157,
    name: "Ursinus College",
    location: "Collegeville, Pennsylvania",
    acceptanceRate: 82.0,
    type: "private",
    avgGPA: 3.37,
    avgSAT: 1180,
  },
  {
    id: 158,
    name: "Susquehanna University",
    location: "Selinsgrove, Pennsylvania",
    acceptanceRate: 76.0,
    type: "private",
    avgGPA: 3.6,
    avgSAT: 1140,
  },
  {
    id: 159,
    name: "Juniata College",
    location: "Huntingdon, Pennsylvania",
    acceptanceRate: 76.0,
    type: "private",
    avgGPA: 3.73,
    avgSAT: 1220,
  },
  {
    id: 160,
    name: "Allegheny College",
    location: "Meadville, Pennsylvania",
    acceptanceRate: 70.0,
    type: "private",
    avgGPA: 3.75,
    avgSAT: 1240,
  },

  // Southern private colleges
  {
    id: 161,
    name: "Davidson College",
    location: "Davidson, North Carolina",
    acceptanceRate: 17.0,
    type: "private",
    avgGPA: 3.91,
    avgSAT: 1405,
  },
  {
    id: 162,
    name: "Furman University",
    location: "Greenville, South Carolina",
    acceptanceRate: 61.0,
    type: "private",
    avgGPA: 3.77,
    avgSAT: 1280,
  },
  {
    id: 163,
    name: "Wofford College",
    location: "Spartanburg, South Carolina",
    acceptanceRate: 64.0,
    type: "private",
    avgGPA: 3.62,
    avgSAT: 1240,
  },
  {
    id: 164,
    name: "Presbyterian College",
    location: "Clinton, South Carolina",
    acceptanceRate: 65.0,
    type: "private",
    avgGPA: 3.54,
    avgSAT: 1140,
  },
  {
    id: 165,
    name: "Converse College",
    location: "Spartanburg, South Carolina",
    acceptanceRate: 56.0,
    type: "private",
    avgGPA: 3.65,
    avgSAT: 1120,
  },
  {
    id: 166,
    name: "High Point University",
    location: "High Point, North Carolina",
    acceptanceRate: 77.0,
    type: "private",
    avgGPA: 3.31,
    avgSAT: 1120,
  },
  {
    id: 167,
    name: "Elon University",
    location: "Elon, North Carolina",
    acceptanceRate: 78.0,
    type: "private",
    avgGPA: 4.09,
    avgSAT: 1240,
  },
  {
    id: 168,
    name: "Guilford College",
    location: "Greensboro, North Carolina",
    acceptanceRate: 84.0,
    type: "private",
    avgGPA: 3.27,
    avgSAT: 1080,
  },
  {
    id: 169,
    name: "Catawba College",
    location: "Salisbury, North Carolina",
    acceptanceRate: 58.0,
    type: "private",
    avgGPA: 3.5,
    avgSAT: 1040,
  },
  {
    id: 170,
    name: "Lenoir-Rhyne University",
    location: "Hickory, North Carolina",
    acceptanceRate: 81.0,
    type: "private",
    avgGPA: 3.56,
    avgSAT: 1080,
  },

  // Midwest private colleges
  {
    id: 171,
    name: "Kenyon College",
    location: "Gambier, Ohio",
    acceptanceRate: 29.0,
    type: "private",
    avgGPA: 3.89,
    avgSAT: 1370,
  },
  {
    id: 172,
    name: "Oberlin College",
    location: "Oberlin, Ohio",
    acceptanceRate: 35.0,
    type: "private",
    avgGPA: 3.6,
    avgSAT: 1350,
  },
  {
    id: 173,
    name: "Denison University",
    location: "Granville, Ohio",
    acceptanceRate: 29.0,
    type: "private",
    avgGPA: 3.9,
    avgSAT: 1320,
  },
  {
    id: 174,
    name: "College of Wooster",
    location: "Wooster, Ohio",
    acceptanceRate: 56.0,
    type: "private",
    avgGPA: 3.64,
    avgSAT: 1240,
  },
  {
    id: 175,
    name: "Ohio Wesleyan University",
    location: "Delaware, Ohio",
    acceptanceRate: 72.0,
    type: "private",
    avgGPA: 3.5,
    avgSAT: 1180,
  },
  {
    id: 176,
    name: "Wittenberg University",
    location: "Springfield, Ohio",
    acceptanceRate: 93.0,
    type: "private",
    avgGPA: 3.28,
    avgSAT: 1120,
  },
  {
    id: 177,
    name: "Hiram College",
    location: "Hiram, Ohio",
    acceptanceRate: 84.0,
    type: "private",
    avgGPA: 3.37,
    avgSAT: 1080,
  },
  {
    id: 178,
    name: "Marietta College",
    location: "Marietta, Ohio",
    acceptanceRate: 84.0,
    type: "private",
    avgGPA: 3.54,
    avgSAT: 1120,
  },
  {
    id: 179,
    name: "Muskingum University",
    location: "New Concord, Ohio",
    acceptanceRate: 74.0,
    type: "private",
    avgGPA: 3.37,
    avgSAT: 1040,
  },
  {
    id: 180,
    name: "Capital University",
    location: "Columbus, Ohio",
    acceptanceRate: 72.0,
    type: "private",
    avgGPA: 3.5,
    avgSAT: 1120,
  },

  // Western colleges
  {
    id: 181,
    name: "Whitman College",
    location: "Walla Walla, Washington",
    acceptanceRate: 48.0,
    type: "private",
    avgGPA: 3.79,
    avgSAT: 1350,
  },
  {
    id: 182,
    name: "Lewis & Clark College",
    location: "Portland, Oregon",
    acceptanceRate: 69.0,
    type: "private",
    avgGPA: 3.74,
    avgSAT: 1280,
  },
  {
    id: 183,
    name: "Willamette University",
    location: "Salem, Oregon",
    acceptanceRate: 81.0,
    type: "private",
    avgGPA: 3.69,
    avgSAT: 1240,
  },
  {
    id: 184,
    name: "University of Puget Sound",
    location: "Tacoma, Washington",
    acceptanceRate: 84.0,
    type: "private",
    avgGPA: 3.64,
    avgSAT: 1240,
  },
  {
    id: 185,
    name: "Seattle University",
    location: "Seattle, Washington",
    acceptanceRate: 85.0,
    type: "private",
    avgGPA: 3.64,
    avgSAT: 1180,
  },
  {
    id: 186,
    name: "Gonzaga University",
    location: "Spokane, Washington",
    acceptanceRate: 70.0,
    type: "private",
    avgGPA: 3.73,
    avgSAT: 1240,
  },
  {
    id: 187,
    name: "Whitworth University",
    location: "Spokane, Washington",
    acceptanceRate: 93.0,
    type: "private",
    avgGPA: 3.74,
    avgSAT: 1180,
  },
  {
    id: 188,
    name: "Pacific Lutheran University",
    location: "Tacoma, Washington",
    acceptanceRate: 93.0,
    type: "private",
    avgGPA: 3.64,
    avgSAT: 1140,
  },
  {
    id: 189,
    name: "Seattle Pacific University",
    location: "Seattle, Washington",
    acceptanceRate: 91.0,
    type: "private",
    avgGPA: 3.65,
    avgSAT: 1140,
  },
  {
    id: 190,
    name: "Western Washington University",
    location: "Bellingham, Washington",
    acceptanceRate: 93.0,
    type: "public",
    avgGPA: 3.46,
    avgSAT: 1120,
  },

  // Final colleges to reach 200+
  {
    id: 191,
    name: "University of West Virginia",
    location: "Morgantown, West Virginia",
    acceptanceRate: 88.0,
    type: "public",
    avgGPA: 3.59,
    avgSAT: 1040,
  },
  {
    id: 192,
    name: "Marshall University",
    location: "Huntington, West Virginia",
    acceptanceRate: 96.0,
    type: "public",
    avgGPA: 3.46,
    avgSAT: 1040,
  },
  {
    id: 193,
    name: "University of Wyoming",
    location: "Laramie, Wyoming",
    acceptanceRate: 96.0,
    type: "public",
    avgGPA: 3.5,
    avgSAT: 1120,
  },
  {
    id: 194,
    name: "University of Alaska Fairbanks",
    location: "Fairbanks, Alaska",
    acceptanceRate: 68.0,
    type: "public",
    avgGPA: 3.37,
    avgSAT: 1080,
  },
  {
    id: 195,
    name: "University of Alaska Anchorage",
    location: "Anchorage, Alaska",
    acceptanceRate: 65.0,
    type: "public",
    avgGPA: 3.27,
    avgSAT: 1040,
  },
  {
    id: 196,
    name: "University of Hawaii at Manoa",
    location: "Honolulu, Hawaii",
    acceptanceRate: 84.0,
    type: "public",
    avgGPA: 3.74,
    avgSAT: 1240,
  },
  {
    id: 197,
    name: "Hawaii Pacific University",
    location: "Honolulu, Hawaii",
    acceptanceRate: 87.0,
    type: "private",
    avgGPA: 3.5,
    avgSAT: 1120,
  },
  {
    id: 198,
    name: "Chaminade University",
    location: "Honolulu, Hawaii",
    acceptanceRate: 93.0,
    type: "private",
    avgGPA: 3.4,
    avgSAT: 1040,
  },
  {
    id: 199,
    name: "Brigham Young University Hawaii",
    location: "Laie, Hawaii",
    acceptanceRate: 34.0,
    type: "private",
    avgGPA: 3.9,
    avgSAT: 1180,
  },
  {
    id: 200,
    name: "Alaska Pacific University",
    location: "Anchorage, Alaska",
    acceptanceRate: 51.0,
    type: "private",
    avgGPA: 3.27,
    avgSAT: 1080,
  },
]
